config/routes.rb
Marko::Application.routes.draw do
  get "users/show"

  resources :posts => [:index, :show, :create]

root :to => 'pages#home'
  get 'about' => 'pages#about'
  match 'index' => 'users#index' 

end

app/models/post.rb
class Post < ActiveRecord::Base
  COORDINATE_DELTA = 0.05

  #attr_accessible :body, :lat, :lng
  has_attached_file :image,
                  :styles => { :thumbnail => "100x100#" },
                  :storage => :s3,
                  :s3_credentials => S3_CREDENTIALS

  #belongs_to :user

  validates :body, presence: true, length: { maximum: 140 }
  #validates :user_id, presence: true
  validates :lat, :lng, :presence => true, :numericality => true

scope :nearby, lambda { |lat, lng|
  where("lat BETWEEN ? AND ?", lat - COORDINATE_DELTA, lat + COORDINATE_DELTA).
  where("lng BETWEEN ? AND ?", lng - COORDINATE_DELTA, lng + COORDINATE_DELTA).
  limit(64)
}

  def as_json(options = nil)
    {
      :lat => self.lat,
      :lng => self.lng,

      :image_urls => {
        :original => self.image.url,
        :thumbnail => self.image.url(:thumbnail)
      },

      :created_at => self.created_at.iso8601
    }
  end
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  # :recoverable, - add this in later when you have an email client setup...
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # commenting this out skips the csrf token authentication - the app is insecure - setup api keys later
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  #commented out only for developmnet
  #before_filter :authenticate_user!

respond_to :json

  def index
    lat, lng = params[:lat], params[:lng]
    if lat and lng
      @posts = Post.nearby(lat.to_f, lng.to_f)
      respond_with({:posts => @posts})
    else
      respond_with({:message => "Invalid or missing lat/lng parameters"}, :status => 406)
    end
  end
#    @posts = Post.order("created_at desc").all(params[:id])
  #  respond_to do |format|
   #   format.html # index.html.erb
    #  format.json { render json: @posts }
    #end
  #end

  def show
    @post = Post.find(params[:id])
    respond_with(@post)
  end
    #respond_to do |format|
     # format.html # show.html.erb
      #format.json { render json: @post }
   # end
  #end

  # def new
   # @post = current_user.posts.new

   # respond_to do |format|
   #   format.html # new.html.erb
   #   format.json { render json: @post }
   # end
  #end

  #def edit
  #  @post = current_user.posts.find(params[:id])
  #end
  def create
    @post = Post.create(params[:post])
    respond_with(@post)
  end
end
  # def create
  #  # this is what it used to be to make it work on web but not iOS @post = current_user.posts.new(params[:post])
  #   @post = Post.new(params[:post])

  #   respond_to do |format|
  #     if @post.save
  #       format.html { redirect_to @post, notice: 'Mark was successfully created.' }
  #       format.json { render json: @post, status: :created, location: @post }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def update
  #   @post = current_user.posts.find(params[:id])

  #   respond_to do |format|
  #     if @post.update_attributes(params[:post])
  #       format.html { redirect_to @post, notice: 'Success!' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @post = current_user.posts.find(params[:id])
  #   @post.destroy

  #   respond_to do |format|
  #     format.html { redirect_to posts_url }
  #     format.json { head :no_content }
  #   end
  # end
#end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	#commented out only for developmnet
	#before_filter :authenticate_user!

	respond_to :json, :xml
  def show
  	@user = User.find(params[:id])
    @posts = @user.posts.all
  end

  respond_to :json, :xml
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
	<%= link_to "Marko", root_path %>
</small>
</div>

app/views/layouts/_header.html.erb
	<div class="navbar navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Marko", root_path, class: "brand" %>

             <div class="nav-collapse">
             <ul class="nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Posts", posts_path %></li>
				<li><%= link_to "Users", index_path %></li>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
								 <li><%= link_to "Add +", new_post_path %></li>
			                     <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
			                     <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			                      <% else %>
			                    	<li><%= link_to "Login", new_user_session_path %></li>
			                      <% end %>
			</ul>
			     </div>
			</div>                      	
	</div>		                      
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marko</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
	<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>What are you about?</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
	<h1>Life is Remarkable.</h1>
	<br>
	<p>
	 <%= link_to "Leave Your Mark", new_user_registration_path, class: "btn btn-large btn-primary" %>
	</p>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :body, as: :text, length: { maximum: 140 }, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
  <span class="body"><%= post.body %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago, at lat:x, lng:x. by 
    <strong>
    		Posted by <%= link_to post.user.name %>
    </strong>.
  </span>
  <% if current_user == post.user %>
    <p>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <% end %>
</li>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Post Index </h1>
  	<ul class="posts">
  		<% if @posts.any? %>

        <%= render@posts %>
        <% end %>
	</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <p>
              <%= @post.body %>
            </p>
            <p>
              <%= @post.user.name %>
            </p>
            <% if current_user == @post.user %>
                <%= link_to 'Edit', edit_post_path(@post) %> |
            <% end %>
            <%= link_to 'Back', posts_path %>

        </div>
    </div>
</div>

app/views/users/_user.html.erb
<li>
<%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<h1> User Index </h1>
  	<ul class="users">
        <%= render@users %>
	</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

	<% if @user.posts.any? %>
	<h3>Posts (<%= @user.posts.count %>)</h3>
	<ol class="posts">
	<%= render @posts %>
</ol>
<% end %>